#!/usr/bin/env python
"""Generate the JevAI mod's posture library.

    python jev_hoi4/jevai/gen_mod.py mod/jevai_probe

A posture is a fixed bundle of AI-only levers: targetless ai_strategy entries (unit/role mix,
production, factory ratio, construction, force concentration) plus a dynamic modifier made only of
ai_* modifiers (how many planes / divisions the AI wants, what it researches). Nothing here gives a
country a gameplay bonus; it only changes what the AI decides. Jev picks one posture per controlled
country; the daemon applies it with console `e TAG jev_set_posture_<k>`. add_ai_strategy is
additive, so every posture has an exact inverse and switching = undo old + apply new. The active
posture is kept in the country variable jev_posture (0 = none) and logged by the monthly telemetry.

Version 2 (2026-09-25): the 2026-09-24 measurement (jevai.effects) showed only 'armored offensive'
and 'total war economy' changed production. v2 fixes the invalid unit_ratio ids (unit_ratio only
covers ships and planes; land units use role_ratio), adds build_building weights, and adds the
ai_* modifiers that scale the AI's wanted army and air force (ai_focus_aviation_factor multiplies
the number of land planes the AI wants, see common/ai_strategy/_documentation.md).
Total war economy is unchanged: it is the reference arm and it already worked.
"""
from __future__ import annotations

import os
import sys

VERSION = 2

# posture name -> list of (strategy type, id or None, value)
POSTURES: dict[str, list[tuple[str, str | None, int]]] = {
    "defensive buildup": [
        ("role_ratio", "infantry", 25), ("role_ratio", "armor", -10), ("role_ratio", "artillery", 25),
        ("role_ratio", "anti_tank", 20), ("equipment_production_factor", "anti_tank", 40),
        ("equipment_production_factor", "anti_air", 30), ("equipment_production_factor", "artillery", 20),
        ("build_building", "bunker", 30), ("force_concentration_factor", None, -15),
    ],
    "industrial expansion": [
        ("added_military_to_civilian_factory_ratio", None, -40), ("build_building", "industrial_complex", 60),
        ("equipment_production_factor", "infantry", -20), ("force_concentration_factor", None, -10),
    ],
    "armored offensive": [
        ("role_ratio", "armor", 25), ("role_ratio", "infantry", -15), ("role_ratio", "motorized", 20),
        ("role_ratio", "mechanized", 10), ("equipment_production_factor", "armor", 50),
        ("equipment_production_factor", "motorized", 30), ("equipment_production_factor", "mechanized", 20),
        ("force_concentration_factor", None, 25),
    ],
    "air power": [
        ("equipment_production_factor", "fighter", 50), ("equipment_production_factor", "cas", 40),
        ("equipment_production_factor", "tactical_bomber", 30), ("unit_ratio", "fighter", 30),
        ("unit_ratio", "cas", 25), ("build_building", "air_base", 30),
    ],
    "naval power": [
        ("dockyard_to_military_factory_ratio", None, 30), ("equipment_production_factor", "screen_ship", 30),
        ("equipment_production_factor", "submarine", 30), ("equipment_production_factor", "capital_ship", 20),
        ("equipment_production_factor", "naval_bomber", 30), ("build_building", "dockyard", 40),
    ],
    "total war economy": [
        ("added_military_to_civilian_factory_ratio", None, 50), ("equipment_production_factor", "infantry", 30),
        ("equipment_production_factor", "artillery", 30), ("force_concentration_factor", None, 15),
    ],
}
# posture name -> ai_* country modifiers applied while the posture is active (AI weights only)
MODIFIERS: dict[str, dict[str, float]] = {
    "defensive buildup": {"ai_desired_divisions_factor": 0.3, "ai_focus_defense_factor": 1.0},
    "industrial expansion": {"ai_focus_peaceful_factor": 0.5},
    "armored offensive": {"ai_focus_aggressive_factor": 0.5, "ai_focus_military_equipment_factor": 0.5},
    "air power": {"ai_focus_aviation_factor": 1.0},
    "naval power": {"ai_focus_naval_factor": 1.0, "ai_focus_naval_air_factor": 0.5},
    "total war economy": {},
}
NAMES = list(POSTURES)  # index + 1 = posture id stored in jev_posture


def entry(t, i, v, sign=1):
    s = f"\t\tadd_ai_strategy = {{ type = {t}"
    if i:
        s += f" id = {i}"
    return s + f" value = {sign * v} }}\n"


def gen_effects() -> str:
    out = [f"# GENERATED by jev_hoi4/jevai/gen_mod.py (postures v{VERSION}) - do not edit by hand.\n",
           "# Postures: " + "; ".join(f"{k + 1}={n}" for k, n in enumerate(NAMES)) + "\n\n"]
    for k, name in enumerate(NAMES, 1):
        s = POSTURES[name]
        dyn = f"\t\tadd_dynamic_modifier = {{ modifier = jev_posture_{k} }}\n" if MODIFIERS[name] else ""
        undyn = f"\t\tremove_dynamic_modifier = {{ modifier = jev_posture_{k} }}\n" if MODIFIERS[name] else ""
        out.append(f"jev_apply_posture_{k} = {{  # {name}\n\tif = {{ limit = {{ always = yes }}\n")
        out += [entry(t, i, v) for t, i, v in s]
        out.append(dyn + "\t}\n}\n")
        out.append(f"jev_undo_posture_{k} = {{\n\tif = {{ limit = {{ always = yes }}\n")
        out += [entry(t, i, v, -1) for t, i, v in s]
        out.append(undyn + "\t}\n}\n")
    out.append("jev_clear_posture = {\n")
    for k in range(1, len(NAMES) + 1):
        out.append(f"\tif = {{ limit = {{ check_variable = {{ jev_posture = {k} }} }} jev_undo_posture_{k} = yes }}\n")
    out.append("\tset_variable = { jev_posture = 0 }\n}\n")
    for k, name in enumerate(NAMES, 1):
        out.append(f"jev_set_posture_{k} = {{  # {name}\n"
                   f"\tif = {{ limit = {{ NOT = {{ check_variable = {{ jev_posture = {k} }} }} }}\n"
                   f"\t\tjev_clear_posture = yes\n\t\tjev_apply_posture_{k} = yes\n"
                   f"\t\tset_variable = {{ jev_posture = {k} }}\n\t}}\n"
                   f"\tlog = \"JEV|ACT|[ROOT.GetTag]|posture={k}\"\n}}\n")
    out.append("jev_set_posture_0 = {\n\tjev_clear_posture = yes\n\tlog = \"JEV|ACT|[ROOT.GetTag]|posture=0\"\n}\n")
    # console handshake: collector/jevd run `e <TAG> jev_ack_<n>` after their commands and wait for the log line
    for n in range(20):
        out.append(f"jev_ack_{n} = {{\n\tlog = \"JEV|ACK|{n}\"\n}}\n")
    return "".join(out)


def gen_modifiers() -> str:
    out = [f"# GENERATED by jev_hoi4/jevai/gen_mod.py (postures v{VERSION}) - AI-only weights, no gameplay bonus.\n\n"]
    for k, name in enumerate(NAMES, 1):
        if not MODIFIERS[name]:
            continue
        out.append(f"jev_posture_{k} = {{  # {name}\n\tenable = {{ always = yes }}\n\ticon = GFX_modifiers_sabotaged_resource\n")
        out += [f"\t{m} = {v}\n" for m, v in MODIFIERS[name].items()]
        out.append("}\n\n")
    return "".join(out)


def main(argv):
    mod = argv[0] if argv else "mod/jevai_probe"
    for sub, name, text in [("scripted_effects", "jev_postures.txt", gen_effects()),
                            ("dynamic_modifiers", "jev_postures.txt", gen_modifiers())]:
        d = os.path.join(mod, "common", sub)
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, name), "w", encoding="utf-8").write(text)
        print("wrote", os.path.join(d, name))


if __name__ == "__main__":
    main(sys.argv[1:])
