"""Posture library of the JevAI mod, and the generator of its script files.

    python -m mods.jevai.runtime.postures    (rewrites mods/jevai/common/*/jevai_postures.txt)

A posture is a fixed bundle of AI-only levers: targetless add_ai_strategy entries (unit/role mix, production,
factory ratios, construction, force concentration) plus a dynamic modifier made only of ai_* modifiers. Nothing
gives a country a gameplay bonus; it only changes what the AI decides. add_ai_strategy is additive, so every
posture has an exact inverse and switching = undo old + apply new. The console applies one with
`e TAG jev_set_posture_<k>`; the active posture is kept in the country variable jev_posture (0 = none).

VERSION 2: unit_ratio only covers ships and planes (land units use role_ratio); build_building weights and the ai_*
modifiers were added; 'total war economy' is unchanged as the reference arm. Games record the version they ran with
(pv) and posture questions name it, because v1 and v2 share names but not content.
"""
from __future__ import annotations

import os

VERSION = 2

# posture name -> list of (strategy type, id or None, value)
POSTURES: dict[str, list[tuple[str, str | None, int]]] = {
    "defensive buildup": [
        ("role_ratio", "infantry", 25), ("role_ratio", "armor", -10), ("role_ratio", "artillery", 25),
        ("role_ratio", "anti_tank", 20), ("equipment_production_factor", "anti_tank", 40),
        ("equipment_production_factor", "anti_air", 30), ("equipment_production_factor", "artillery", 20),
        ("build_building", "bunker", 30), ("force_concentration_factor", None, -15),
    ],
    "industrial expansion": [
        ("added_military_to_civilian_factory_ratio", None, -40), ("build_building", "industrial_complex", 60),
        ("equipment_production_factor", "infantry", -20), ("force_concentration_factor", None, -10),
    ],
    "armored offensive": [
        ("role_ratio", "armor", 25), ("role_ratio", "infantry", -15), ("role_ratio", "motorized", 20),
        ("role_ratio", "mechanized", 10), ("equipment_production_factor", "armor", 50),
        ("equipment_production_factor", "motorized", 30), ("equipment_production_factor", "mechanized", 20),
        ("force_concentration_factor", None, 25),
    ],
    "air power": [
        ("equipment_production_factor", "fighter", 50), ("equipment_production_factor", "cas", 40),
        ("equipment_production_factor", "tactical_bomber", 30), ("unit_ratio", "fighter", 30),
        ("unit_ratio", "cas", 25), ("build_building", "air_base", 30),
    ],
    "naval power": [
        ("dockyard_to_military_factory_ratio", None, 30), ("equipment_production_factor", "screen_ship", 30),
        ("equipment_production_factor", "submarine", 30), ("equipment_production_factor", "capital_ship", 20),
        ("equipment_production_factor", "naval_bomber", 30), ("build_building", "dockyard", 40),
    ],
    "total war economy": [
        ("added_military_to_civilian_factory_ratio", None, 50), ("equipment_production_factor", "infantry", 30),
        ("equipment_production_factor", "artillery", 30), ("force_concentration_factor", None, 15),
    ],
}
# posture name -> ai_* country modifiers applied while the posture is active (AI weights only)
MODIFIERS: dict[str, dict[str, float]] = {
    "defensive buildup": {"ai_desired_divisions_factor": 0.3, "ai_focus_defense_factor": 1.0},
    "industrial expansion": {"ai_focus_peaceful_factor": 0.5},
    "armored offensive": {"ai_focus_aggressive_factor": 0.5, "ai_focus_military_equipment_factor": 0.5},
    "air power": {"ai_focus_aviation_factor": 1.0},
    "naval power": {"ai_focus_naval_factor": 1.0, "ai_focus_naval_air_factor": 0.5},
    "total war economy": {},
}
NAMES = list(POSTURES)  # index + 1 = posture id k (jev_set_posture_k, jev_posture)
ACKS = 20  # jev_ack_0..19: the console handshake (console.py)
MOD_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = f"GENERATED by mods/jevai/runtime/postures.py (postures v{VERSION})"


def _entry(t: str, i: str | None, v: int, sign: int = 1) -> str:
    s = f"\t\tadd_ai_strategy = {{ type = {t}"
    if i:
        s += f" id = {i}"
    return s + f" value = {sign * v} }}\n"


def effects() -> str:
    """common/scripted_effects: apply and undo per posture, clear, set (logs JEV|ACT), and the ack effects."""
    out = [f"# {HEADER} - do not edit by hand.\n",
           "# Postures: " + "; ".join(f"{k + 1}={n}" for k, n in enumerate(NAMES)) + "\n\n"]
    for k, name in enumerate(NAMES, 1):
        dyn = f"\t\tadd_dynamic_modifier = {{ modifier = jev_posture_{k} }}\n" if MODIFIERS[name] else ""
        undyn = f"\t\tremove_dynamic_modifier = {{ modifier = jev_posture_{k} }}\n" if MODIFIERS[name] else ""
        out.append(f"jev_apply_posture_{k} = {{  # {name}\n\tif = {{ limit = {{ always = yes }}\n")
        out += [_entry(*e) for e in POSTURES[name]]
        out.append(dyn + "\t}\n}\n")
        out.append(f"jev_undo_posture_{k} = {{\n\tif = {{ limit = {{ always = yes }}\n")
        out += [_entry(*e, -1) for e in POSTURES[name]]
        out.append(undyn + "\t}\n}\n")
    out.append("jev_clear_posture = {\n")
    for k in range(1, len(NAMES) + 1):
        out.append(f"\tif = {{ limit = {{ check_variable = {{ jev_posture = {k} }} }} jev_undo_posture_{k} = yes }}\n")
    out.append("\tset_variable = { jev_posture = 0 }\n}\n")
    for k, name in enumerate(NAMES, 1):
        out.append(f"jev_set_posture_{k} = {{  # {name}\n"
                   f"\tif = {{ limit = {{ NOT = {{ check_variable = {{ jev_posture = {k} }} }} }}\n"
                   f"\t\tjev_clear_posture = yes\n\t\tjev_apply_posture_{k} = yes\n"
                   f"\t\tset_variable = {{ jev_posture = {k} }}\n\t}}\n"
                   f"\tlog = \"JEV|ACT|[ROOT.GetTag]|posture={k}\"\n}}\n")
    out.append("jev_set_posture_0 = {\n\tjev_clear_posture = yes\n\tlog = \"JEV|ACT|[ROOT.GetTag]|posture=0\"\n}\n")
    # the runner's orders (runner.py): each AI country's wanted posture in jev_want; applied once when it changes, and
    # only in the mode the player chose at game start (events/jevai.txt): all AI countries, or major powers only
    out.append("jev_follow_orders = {\n\tif = { limit = { is_ai = yes NOT = { check_variable = { jev_want = jev_posture } } "
               "OR = { has_global_flag = jevai_mode_all AND = { has_global_flag = jevai_mode_majors is_major = yes } } }\n")
    for k in range(0, len(NAMES) + 1):
        out.append(f"\t\tif = {{ limit = {{ check_variable = {{ jev_want = {k} }} }} jev_set_posture_{k} = yes }}\n")
    out.append("\t}\n}\n")
    for n in range(ACKS):
        out.append(f"jev_ack_{n} = {{\n\tlog = \"JEV|ACK|{n}\"\n}}\n")
    return "".join(out)


def modifiers() -> str:
    """common/dynamic_modifiers: one AI-weights-only modifier per posture that has any."""
    out = [f"# {HEADER} - AI-only weights, no gameplay bonus.\n\n"]
    for k, name in enumerate(NAMES, 1):
        if MODIFIERS[name]:
            out.append(f"jev_posture_{k} = {{  # {name}\n\tenable = {{ always = yes }}\n\ticon = GFX_modifiers_sabotaged_resource\n")
            out += [f"\t{m} = {v}\n" for m, v in MODIFIERS[name].items()]
            out.append("}\n\n")
    return "".join(out)


def main():
    for sub, text in (("scripted_effects", effects()), ("dynamic_modifiers", modifiers())):
        path = os.path.join(MOD_DIR, "common", sub, "jevai_postures.txt")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote", path)


if __name__ == "__main__":
    main()
